function getDropdownData() {
  const cache = CacheService.getScriptCache();
  const cached = cache.get("dropdown_data_v1");
  if (cached) return JSON.parse(cached);
  const data = {
    state: [
      "Andaman and Nicobar",
      "Andhra Pradesh",
      "Arunachal Pradesh",
      "Assam",
      "Bihar",
      "Chandigarh",
      "Chattisgarh",
      "Daman, Diu, Dadra and Nagar Haveli",
      "Delhi",
      "Goa",
      "Gujarat",
      "Haryana",
      "Himachal Pradesh",
      "Jammu & Kashmir",
      "Jharkhand",
      "Karnataka",
      "Kerala",
      "Ladakh",
      "Lakshadweep",
      "Madhya Pradesh",
      "Maharashtra",
      "Manipur",
      "Meghalaya",
      "Mizoram",
      "Nagaland",
      "Odisha",
      "Puducherry",
      "Punjab",
      "Rajasthan",
      "Sikkim",
      "Tamil Nadu",
      "Telangana",
      "Tripura",
      "Uttar Pradesh",
      "Uttarakhand",
      "West Bengal",
    ],
    workType: [
      "AAM",
      "ADR",
      "AIR",
      "CCR",
      "CEO",
      "CFP",
      "CRE",
      "CRZ",
      "CTE",
      "CTO",
      "DIC",
      "DUA",
      "EAM",
      "EAS",
      "EBD",
      "ECC",
      "ECE",
      "ECO",
      "ECP",
      "ECR",
      "ECV",
      "EEO",
      "EFA",
      "EFC",
      "EGA",
      "EIA",
      "EMP",
      "ENA",
      "ENC",
      "ENS",
      "EPH",
      "EPO",
      "EPR",
      "ESD",
      "ESI",
      "FCA",
      "FEO",
      "FLA",
      "FOR",
      "GWC",
      "HAZ",
      "HWM",
      "IMP",
      "INA",
      "LCA",
      "LCS",
      "LIM",
      "MON",
      "MPA",
      "NCC",
      "NEC",
      "NOA",
      "PLA",
      "QRA",
      "SFA",
      "SIL",
      "SOA",
      "STK",
      "TAM",
      "TEC",
      "TOR",
      "WAT",
      "WLC",
      "WPM",
      "WTA",
      "EEX",
      "SEC",
      "other",
    ],
    sector: [
      "1A",
      "1B",
      "1D",
      "2A",
      "2B",
      "3A",
      "3B",
      "4A",
      "4B",
      "4C",
      "4D",
      "4F",
      "5A",
      "5B",
      "5C",
      "5D",
      "5E",
      "5F",
      "5G",
      "5H",
      "5J",
      "6A",
      "6B",
      "7A",
      "7B",
      "7C",
      "7D",
      "7DA",
      "7E",
      "7F",
      "7G",
      "7H",
      "7I",
      "8A",
      "8B",
      "71",
      "72",
      "73",
      "74",
      "75",
      "76",
      "77",
      "78",
      "79",
      "80",
      "81",
      "82",
      "N/A",
      "others",
    ],
    specs: [
      "NA0",
      "GA0",
      "GB1",
      "GB2",
      "GTA",
      "GEA",
      "GEX",
      "GTR",
      "GPL",
      "BA0",
      "BB1",
      "BB2",
      "BTA",
      "BEA",
      "BTR",
      "BPL",
      "CG1",
      "CG2",
    ],
    team: [
      "Arctic",
      "Canal",
      "Cove",
      "Creek",
      "Delta",
      "Estuary",
      "Fountain",
      "Glacier",
      "Lagoon",
      "Lakes",
      "Oasis",
      "Ocean",
      "Pond",
      "Pool",
      "Reservoir",
      "River",
      "Spring",
      "Tributary",
      "Upstream",
      "N/A",
    ],
    functionalArea: [
      "AP",
      "AQ",
      "EB",
      "GEO",
      "HG",
      "HW",
      "LU",
      "NV",
      "RH",
      "SC",
      "SE",
      "SHW",
      "SW",
      "WP",
    ],
    faa: [
      "Ankita Singh",
      "Deepak Kumar",
      "Ghanshyam Kumar",
      "Hari om Kanaujiya",
      "Kushal Bhargava",
      "Muthukumaran Ganpathi Narayanan",
      "Navneet Kaur",
      "Neha Mehra",
      "Pramod Kumar",
      "Rajesh Kumar",
      "Sadaf Akhtar",
      "Sakshi Tripathi",
      "Tanya Thakur",
    ],
    month: [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December",
    ],
    faeCatB: [
      "Akta Chugh",
      "Chandra Shekhar Jha",
      "Charmi Shah",
      "Deepika Arora",
      "Dipak Anand",
      "Disha Patel",
      "Dr. Anil Kumar",
      "Jagdishchandra Anchlanand Rathi",
      "Manoj Pant",
      "Megha Solanki",
      "Muthukumaran Ganpathi Narayanan",
      "Neha Aggarwal",
      "Dr.Nipun Bhargava",
      "Partho Sarathi Mukherjee",
      "Pramod Kumar",
      "Rachna Bhargava",
      "Rachna Dogra",
      "Rajneesh Kumar Maurya",
      "Ramdas Atmaram Wani",
      "Richa Aggarwal",
      "Saloni Sharma",
      "Santosh Pant",
      "Shweta Rajput",
      "Sreeja Sreekanth",
      "Tulika Rawat",
      "Urvi Pritam",
      "Vimmi Sagar",
    ],
    faeCatA: [
      "Akta Chugh",
      "Alok Agrwal",
      "Disha Patel",
      "Mamta Pandey",
      "Manoj Pant",
      "Muthukumaran Ganpathi Narayanan",
      "Neha Aggarwal",
      "Dr. Nipun Bhargava",
      "Partho Sarathi Mukherjee",
      "Praveen Bhargava",
      "Rachna Bhargava",
      "Rachna Dogra",
      "Rahul Deshmukh",
      "Rajneesh Kumar Maurya",
      "Ramdas Atmaram Wani",
      "Saloni Sharma",
      "Santosh Pant",
      "Tulika Rawat",
    ],
    eac: [
      "Coal Mining",
      "Non-Coal Mining",
      "CRZ",
      "Hydro & River Valley",
      "Industry-1 (Mineral Based industries)",
      "Industry-2 (Petro-chemical & Distilleries)",
      "Industry-3 (Chemical Industries)",
      "Infrastructure-1",
      "Infrastructure-2",
      "Nuclear & Defence",
      "Thermal",
      "Violation Cases",
      "PCB",
      "SPCB",
      "DPCC",
      "Andaman and Nicobar SEAC/SEIAA",
      "Andhra Pradesh SEAC/SEIAA",
      "Arunachal Pradesh SEAC/SEIAA",
      "Assam SEAC/SEIAA",
      "Bihar SEAC/SEIAA",
      "Chandigarh SEAC/SEIAA",
      "Chattisgarh SEAC/SEIAA",
      "Daman, Diu, Dadra and Nagar Haveli SEAC/SEIAA",
      "Delhi SEAC/SEIAA",
      "Goa SEAC/SEIAA",
      "Gujarat SEAC/SEIAA",
      "Haryana SEAC/SEIAA",
      "Himachal Pradesh SEAC/SEIAA",
      "Jammu & Kashmir SEAC/SEIAA",
      "Jharkhand SEAC/SEIAA",
      "Karnataka SEAC/SEIAA",
      "Kerala SEAC/SEIAA",
      "Ladakh SEAC/SEIAA",
      "Lakshadweep SEAC/SEIAA",
      "Madhya Pradesh SEAC/SEIAA",
      "Maharashtra SEAC/SEIAA",
      "Manipur SEAC/SEIAA",
      "Meghalaya SEAC/SEIAA",
      "Mizoram SEAC/SEIAA",
      "Nagaland SEAC/SEIAA",
      "Odisha SEAC/SEIAA",
      "Puducherry SEAC/SEIAA",
      "Punjab SEAC/SEIAA",
      "Rajasthan SEAC/SEIAA",
      "Sikkim SEAC/SEIAA",
      "Tamil Nadu SEAC/SEIAA",
      "Telangana SEAC/SEIAA",
      "Tripura SEAC/SEIAA",
      "Uttar Pradesh SEAC/SEIAA",
      "Uttarakhand SEAC/SEIAA",
      "West Bengal SEAC/SEIAA",
      "N/A",
    ],
    eiaCoordinator: [
      "Alok Agrwal",
      "Dr. Anil Kumar",
      "Dr. Nipun Bhargava",
      "Deepika Arora",
      "Disha Patel",
      "Kantharaj Kempanna",
      "Muthukumaran Ganpathi Narayanan",
      "Neha Aggarwal",
      "Partho Sarthi Mukherjee",
      "Praveen Bhargava",
      "Rachna Bhargava",
      "Rajneesh Kumar Maurya",
      "Ramdas Atmaram Wani",
      "Richa Aggarwal",
      "Saloni Sharma",
      "Santosh Pant",
      "Dr. Suresh Chandra Jain",
      "N/A",
    ],
    country: [
      "Afghanistan",
      "Albania",
      "Algeria",
      "Andorra",
      "Angola",
      "Antigua and Barbuda",
      "Argentina",
      "Armenia",
      "Australia",
      "Austria",
      "Azerbaijan",
      "Bahamas",
      "Bahrain",
      "Bangladesh",
      "Barbados",
      "Belarus",
      "Belgium",
      "Belize",
      "Benin",
      "Bhutan",
      "Bolivia",
      "Bosnia and Herzegovina",
      "Botswana",
      "Brazil",
      "Brunei Darussalam",
      "Bulgaria",
      "Burkina Faso",
      "Burundi",
      "Cabo Verde",
      "Cambodia",
      "Cameroon",
      "Canada",
      "Central African Republic",
      "Chad",
      "Chile",
      "China",
      "Colombia",
      "Comoros",
      "Congo (Congo-Brazzaville)",
      "Costa Rica",
      "Croatia",
      "Cuba",
      "Cyprus",
      "Czechia (Czech Republic)",
      "Democratic Republic of the Congo",
      "Denmark",
      "Djibouti",
      "Dominica",
      "Dominican Republic",
      "Ecuador",
      "Egypt",
      "El Salvador",
      "Equatorial Guinea",
      "Eritrea",
      "Estonia",
      "Eswatini (fmr. 'Swaziland')",
      "Ethiopia",
      "Fiji",
      "Finland",
      "France",
      "Gabon",
      "Gambia",
      "Georgia",
      "Germany",
      "Ghana",
      "Greece",
      "Grenada",
      "Guatemala",
      "Guinea",
      "Guinea-Bissau",
      "Guyana",
      "Haiti",
      "Holy See",
      "Honduras",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Iraq",
      "Ireland",
      "Israel",
      "Italy",
      "Jamaica",
      "Japan",
      "Jordan",
      "Kazakhstan",
      "Kenya",
      "Kiribati",
      "Kuwait",
      "Kyrgyzstan",
      "Laos",
      "Latvia",
      "Lebanon",
      "Lesotho",
      "Liberia",
      "Libya",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Madagascar",
      "Malawi",
      "Malaysia",
      "Maldives",
      "Mali",
      "Malta",
      "Marshall Islands",
      "Mauritania",
      "Mauritius",
      "Mexico",
      "Micronesia",
      "Moldova",
      "Monaco",
      "Mongolia",
      "Montenegro",
      "Morocco",
      "Mozambique",
      "Myanmar (formerly Burma)",
      "Namibia",
      "Nauru",
      "Nepal",
      "Netherlands",
      "New Zealand",
      "Nicaragua",
      "Niger",
      "Nigeria",
      "North Korea",
      "North Macedonia (formerly Macedonia)",
      "Norway",
      "Oman",
      "Pakistan",
      "Palau",
      "Palestine State",
      "Panama",
      "Papua New Guinea",
      "Paraguay",
      "Peru",
      "Philippines",
      "Poland",
      "Portugal",
      "Qatar",
      "Romania",
      "Russia",
      "Rwanda",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Vincent and the Grenadines",
      "Samoa",
      "San Marino",
      "Sao Tome and Principe",
      "Saudi Arabia",
      "Senegal",
      "Serbia",
      "Seychelles",
      "Sierra Leone",
      "Singapore",
      "Slovakia",
      "Slovenia",
      "Solomon Islands",
      "Somalia",
      "South Africa",
      "South Korea",
      "South Sudan",
      "Spain",
      "Sri Lanka",
      "Sudan",
      "Suriname",
      "Sweden",
      "Switzerland",
      "Syria",
      "Tajikistan",
      "Tanzania",
      "Thailand",
      "Timor-Leste",
      "Togo",
      "Tonga",
      "Trinidad and Tobago",
      "Tunisia",
      "Turkey",
      "Turkmenistan",
      "Tuvalu",
      "Uganda",
      "Ukraine",
      "United Arab Emirates",
      "United Kingdom",
      "United States of America",
      "Uruguay",
      "Uzbekistan",
      "Vanuatu",
      "Venezuela",
      "Vietnam",
      "Yemen",
      "Zambia",
      "Zimbabwe",
    ],
    stUt: [
      "AP",
      "AR",
      "AS",
      "BR",
      "CG",
      "GA",
      "GJ",
      "HR",
      "HP",
      "JH",
      "KA",
      "KL",
      "MP",
      "MH",
      "MN",
      "ML",
      "MZ",
      "NL",
      "OR",
      "PB",
      "RJ",
      "SK",
      "TN",
      "TG",
      "TR",
      "UP",
      "UT",
      "WB",
      "AN",
      "CH",
      "DN",
      "DD",
      "DL",
      "JK",
      "LA",
      "LD",
      "PY",
    ],
    pgCompany: ["PE", "PS", "PR", "PW"],
    tfNames: [
      "TF - Documents Review Form",
      "TF - for Initial Pages",
      "TF - for Job Allocation",
      "TF - for Updated TRF",
      "TF01",
      "TF02",
      "TF03",
      "TF04",
      "TF05",
      "TF06",
      "TF07",
      "TF08",
      "TF09",
      "TF10",
      "TF21 P Sol",
      "TF22",
      "TF31 PRPL",
    ],
    designations: ["AH", "FE2", "FE3", "BE1", "BE2", "BE3", "TA", "Intern"],
    statuses: ["Complete", "In progress", "Blocked"],
    milestones: [
      "ToR Submission",
      "ToR Letter",
      "EC Application submission",
      "EC Letter issued",
      "Public Hearing",
      "EAC/ SEAC appraisal",
      "Conservation Plan",
      "EIA Report submission",
      "EIA for PH",
      "Life cycle assessment report submission/ prepared",
      "Carbon Footprint",
      "QRA submission",
      "Other",
    ],
    gstTreatment: [
      "PESPL Delhi",
      "PESPL LKO",
      "PESPL Gujarat",
      "PESPL Chennai",
      "PRPL Delhi",
      "PRPL Gurgaon",
      "PS Delhi",
      "PS Gurgaon",
      "PWMPL Delhi",
      "PAWSPL Delhi",
    ],
    prMode: ["PPIP", "PPTP", "PPNP"],
    csuite: [
      "Praveen Bhargava",
      "Rachna Bhargava",
      "Dr. Nipun Bhargava",
      "Kushal Bhargava",
    ],
    category: ["A", "B1", "B2", "N/A"],
    categoryAdvanced: [
      "A as per 7ii",
      "A with PH",
      "A without PH",
      "Amendment",
      "B1 as per 7ii",
      "B1 with GC",
      "B1 with PH",
      "B1 without PH",
      "B2",
      "B2 with GC",
      "Extension",
      "NIPL",
    ],
    baselineSeason: [
      "Summer (Mar to May)",
      "Post-monsoon (Oct to Dec)",
      "Winter (Dec to Feb)",
      "N/A",
      "others",
    ],
    tf22ServiceTypes: ["Submission", "Closure", "Grant", "Completion", "Other"],
    meetingType: [
      "ADS Reply",
      "Environmental Clearance",
      "EIA",
      "TOR",
      "Others",
    ],
    qccReviewer: [
      "All QCC members",
      "Bidhu Bhushan Barman",
      "Dr. Anil Kumar",
      "Dr. Nipun Bhargava",
      "Dr. Suresh Chandra Jain",
      "Kantharaj Kempanna",
      "Muthukumaran Ganpathi Narayanan",
      "Neha Aggarwal",
      "Praveen Bhargava",
      "Rachna Bhargava",
      "Rajneesh Srivasatava",
      "Santosh Pant",
    ],
    tf05PresentationTypes: [
      "EC B2",
      "TOR Appraisal",
      "EIA Appraisal",
      "Reconsideration PPT",
      "Other",
    ],
    tf25TypeOfCase: [
      "New Project",
      "Expansion",
      "Modernization",
      "Transfer of EC",
      "ADS",
      "Other",
    ],
    tf24TypeOfCase: ["TOR stage", "EIA stage", "Ammendment case"],
    hrScore: ["Excellent", "Very Good", "Good", "Average", "Below Average"],
    hrRecommendation: ["Selected", "Rejected", "On Hold"],
    fq10WorkType: [
      "EIA/EMP",
      "ECE",
      "EEO",
      "EPH",
      "ECR",
      "EFC",
      "EPO",
      "EAM",
      "NEC",
      "ECC",
      "CRZ",
      "CRE",
      "FOR",
      "TOR",
      "LCA",
      "NCC",
      "TAM",
      "CFP",
      "ECV",
      "ESI",
      "ECP",
      "EAS",
      "EPR",
      "LCS",
      "PLA",
      "WLC",
      "FCA",
      "TEC",
      "ECO",
      "ENA",
      "CTE",
      "CTO",
      "CEO",
      "MON",
      "EGA",
      "DUA",
      "ENC",
      "ESD",
      "ENS",
      "STK",
      "WPM",
      "AAM",
      "EFA",
      "SOA",
      "WAT",
      "AIR",
      "EBD",
      "ADR",
      "IMP",
      "NOA",
      "WTA",
      "GWC",
      "GWC",
      "QRA",
      "HAZ",
      "SFA",
      "LIM",
      "FEO",
      "SIL",
      "MPA",
    ],
    fq11TypeOfRoad: ["National Highway", "State Highway", "Village Road"],
    qccTypeOfDocument: [
      "ADS reply",
      "Detailed Project Report",
      "EC Amendment application",
      "EC Corrigendum application",
      "EC Transfer application",
      "EC application",
      "EDS reply",
      "EIA",
      "Executive Summary",
      "NIPL report",
      "PFR",
      "PPT",
      "TOR Amendment application",
      "TOR Corrigendum application",
      "TOR Transfer application",
    ],
    qccStageOfCase: [
      "ADS during EC",
      "ADS during TOR",
      "Detailed Project Report",
      "EC Amendment Appraisal",
      "EC Amendment Submission",
      "EC Appraisal",
      "EC Corrigendum Appraisal",
      "EC Corrigendum Submission",
      "EC Submission",
      "EC Transfer Appraisal",
      "EC Transfer Submission",
      "EDS during EC",
      "EDS during TOR",
      "NIPL appraisal",
      "NIPL submission",
      "PH Appraisal",
      "PH Submission",
      "Reconsideration Appraisal during EC",
      "Reconsideration Appraisal during TOR",
      "TOR Amendment Appraisal",
      "TOR Amendment Submission",
      "TOR Appraisal",
      "TOR Corrigendum Appraisal",
      "TOR Corrigendum Submission",
      "TOR Submission",
      "TOR Transfer Appraisal",
      "TOR Transfer Submission",
    ],
    tmToFAE: [
      "Anshul Aggarwal",
      "Charmi Shah",
      "Deepak Kumar",
      "Deepika Arora",
      "Disha Patel",
      "Hari Prasad Gupta",
      "Manoj Kumar Joshi",
      "Meenakshi Yadav",
      "Megha Solanki",
      "Mitu Mewada",
      "Navneet Kaur",
      "Nikita Bhagat",
      "Nitish Paswan",
      "Paromita Das",
      "Prema Bisht",
      "Rashi Srivastava",
      "Ravi Sharma",
      "Richa Aggarwal",
      "Sadaf Akhtar",
      "Sakshi Dahiya",
      "Sreeja Sreekanth",
      "Tanya Thakur",
    ],
  };
  cache.put("dropdown_data_v1", JSON.stringify(data), 300); // cache 5 minutes
  return data;
}

function getNameEmailMap() {
  return {
    "All QCC members": "qc.council@perfactgroup.in",
    "Bidhu Bhushan Barman": "",
    "Alok Agrwal": "alok.agrwal@perfactgroup.in",
    "Dr. Anil Kumar": "dr.anilkumar@perfactgroup.in",
    "Dr. Nipun Bhargava": "nipunbhargava@perfactgroup.in",
    "Dr. Suresh Chandra Jain": "suresh.jain@perfactgroup.in",
    "Deepika Arora": "deepika.arora@perfactgroup.in",
    "Disha Patel": "disha.patel@perfactgroup.in",
    "Kantharaj Kempanna": "kantharaj.kempanna@perfactgroup.in",
    "Kushal Bhargava": "kushalbhargava@perfactgroup.in",
    "Muthukumaran Ganpathi Narayanan": "gmk@perfactgroup.in",
    "Neha Aggarwal": "neha.aggarwal@perfactgroup.in",
    "Partho Sarthi Mukherjee": "partho.mukherjee@perfactgroup.in",
    "Praveen Bhargava": "praveenbhargava@perfactgroup.in",
    "Rachna Bhargava": "rachnabhargava@perfactgroup.in",
    "Rajneesh Kumar Maurya": "rajneesh.maurya@perfactgroup.in",
    "Rajneesh Srivasatava": "rajneesh.srivasatava@perfactgroup.in",
    "Ramdas Atmaram Wani": "",
    "Richa Aggarwal": "richa.aggarwal@perfactgroup.in",
    "Saloni Sharma": "",
    "Santosh Pant": "santosh.pant@perfactgroup.in",
    "Ankita Singh": "ankita.singh@perfactgroup.in",
    "Deepak Kumar": "deepak.kumar@perfactgroup.in",
    "Ghanshyam Kumar": "ghanshyam.kumar@perfactgroup.in",
    "Hari om Kanaujiya": "hariom.kanaujiya@perfactgroup.in",
    "Navneet Kaur": "navneet.kaur@perfactgroup.in",
    "Neha Mehra": "",
    "Pramod Kumar": "pramod.kumar@perfactgroup.in",
    "Rajesh Kumar": "rajesh.kumar@perfactgroup.in",
    "Sadaf Akhtar": "sadaf.akhtar@perfactgroup.in",
    "Sakshi Tripathi": "sakshi.tripathi@perfactgroup.in",
    "Tanya Thakur": "tanya.thakur@perfactgroup.in",
    "Akta Chugh": "",
    "Chandra Shekhar Jha": "",
    "Charmi Shah": "charmi.shah@perfactgroup.in",
    "Dipak Anand": "dipak.anand@perfactgroup.in",
    "Jagdishchandra Anchlanand Rathi": "",
    "Manoj Pant": "manoj.pant@perfactgroup.in",
    "Megha Solanki": "megha.solanki@perfactgroup.in",
    "Rachna Dogra": "rachna.dogra@perfactgroup.in",
    "Shweta Rajput": "shweta.rajput@perfactgroup.in",
    "Sreeja Sreekanth": "sreeja.sreekanth@perfactgroup.in",
    "Tulika Rawat": "tulika.rawat@perfactgroup.in",
    "Urvi Pritam": "",
    "Vimmi Sagar": "vimmi.sagar@perfactgroup.in",
    "Mamta Pandey": "",
    "Rahul Deshmukh": "rahul.deshmukh@perfactgroup.in",
    "Anshul Aggarwal": "anshul.aggarwal@perfactgroup.in",
    "Hari Prasad Gupta": "hariprasad.gupta@perfactgroup.in",
    "Manoj Kumar Joshi": "manoj.joshi@perfactgroup.in",
    "Meenakshi Yadav": "meenakshi.yadav@perfactgroup.in",
    "Mitu Mewada": "mitu.mewada@perfactgroup.in",
    "Nikita Bhagat": "nikita.bhagat@perfactgroup.in",
    "Nitish Paswan": "",
    "Paromita Das": "paromita.das@perfactgroup.in",
    "Prema Bisht": "prema.bisht@perfactgroup.in",
    "Rashi Srivastava": "",
    "Ravi Sharma": "",
    "Sakshi Dahiya": "sakshi.dahiya@perfactgroup.in",
    "N/A": "",
  };
}

function getEmailByName(name) {
  const map = getNameEmailMap();
  const key = String(name || "");
  return map[key] || "";
}
