function getDropdownData() {
  const cache = CacheService.getScriptCache();
  const cached = cache.get("dropdown_data_v1");
  if (cached) return JSON.parse(cached);
  const data = {
    state: [
      "Andaman and Nicobar",
      "Andhra Pradesh",
      "Arunachal Pradesh",
      "Assam",
      "Bihar",
      "Chandigarh",
      "Chattisgarh",
      "Daman, Diu, Dadra and Nagar Haveli",
      "Delhi",
      "Goa",
      "Gujarat",
      "Haryana",
      "Himachal Pradesh",
      "Jammu & Kashmir",
      "Jharkhand",
      "Karnataka",
      "Kerala",
      "Ladakh",
      "Lakshadweep",
      "Madhya Pradesh",
      "Maharashtra",
      "Manipur",
      "Meghalaya",
      "Mizoram",
      "Nagaland",
      "Odisha",
      "Puducherry",
      "Punjab",
      "Rajasthan",
      "Sikkim",
      "Tamil Nadu",
      "Telangana",
      "Tripura",
      "Uttar Pradesh",
      "Uttarakhand",
      "West Bengal",
    ],
    typeofWork: [
      "AAM",
      "ADR",
      "AIR",
      "CEO",
      "CFP",
      "CRE",
      "CRZ",
      "CTE",
      "CTO",
      "DUA",
      "EAM",
      "EAS",
      "EBD",
      "ECC",
      "ECE",
      "ECO",
      "ECP",
      "ECR",
      "ECV",
      "EEO",
      "EFA",
      "EFC",
      "EGA",
      "EIA",
      "EMP",
      "ENA",
      "ENC",
      "ENS",
      "EPH",
      "EPO",
      "EPR",
      "ESD",
      "ESI",
      "FCA",
      "FEO",
      "FOR",
      "GWC",
      "HAZ",
      "IMP",
      "LCA",
      "LCS",
      "LIM",
      "MON",
      "MPA",
      "NCC",
      "NEC",
      "NOA",
      "PLA",
      "QRA",
      "SFA",
      "SIL",
      "SOA",
      "STK",
      "TAM",
      "TEC",
      "TOR",
      "WAT",
      "WLC",
      "WPM",
      "WTA",
      "other",
    ],
    sector: [
      "1A",
      "1B",
      "1D",
      "2A",
      "2B",
      "3A",
      "3B",
      "4A",
      "4B",
      "4C",
      "4D",
      "4F",
      "5A",
      "5B",
      "5C",
      "5D",
      "5E",
      "5F",
      "5G",
      "5H",
      "5J",
      "6A",
      "6B",
      "7A",
      "7B",
      "7C",
      "7D",
      "7DA",
      "7E",
      "7F",
      "7G",
      "7H",
      "7I",
      "8A",
      "8B",
      "71",
      "72",
      "73",
      "74",
      "75",
      "76",
      "77",
      "78",
      "79",
      "80",
      "81",
      "82",
      "N/A",
      "others",
    ],
    specs: [
      "NA0",
      "GA0",
      "GB1",
      "GB2",
      "GTA",
      "GEA",
      "GTR",
      "GPL",
      "BA0",
      "BB1",
      "BB2",
      "BTA",
      "BEA",
      "BTR",
      "BPL",
      "CG1",
      "CG2",
    ],
    team: [
      "Arctic",
      "Canal",
      "Cove",
      "Creek",
      "Delta",
      "Estuary",
      "Fountain",
      "Glacier",
      "Lagoon",
      "Lakes",
      "Oasis",
      "Ocean",
      "Pond",
      "Pool",
      "Reservoir",
      "River",
      "Spring",
      "Tributary",
      "Upstream",
      "N/A",
    ],
    functionalArea: [
      "AP",
      "AQ",
      "EB",
      "GEO",
      "HG",
      "HW",
      "LU",
      "NV",
      "RH",
      "SC",
      "SE",
      "SHW",
      "SW",
      "WP",
    ],
    faa: [
      "Ankita Singh",
      "Deepak Kumar",
      "Ghanshyam Kumar",
      "Hari om Kanaujiya",
      "Kushal Bhargava",
      "Muthukumaran Ganpathi Narayanan",
      "Navneet Kaur",
      "Neha Mehra",
      "Pramod Kumar",
      "Rajesh Kumar",
      "Sadaf Akhtar",
      "Sakshi Tripathi",
      "Tanya Thakur",
    ],
    month: [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December",
    ],
    faeCatB: [
      "Akta Chugh",
      "Chandra Shekhar Jha",
      "Charmi Shah",
      "Deepika Arora",
      "Dipak Anand",
      "Disha Patel",
      "Dr. Anil Kumar",
      "Jagdishchandra Anchlanand Rathi",
      "Manoj Pant",
      "Megha Solanki",
      "Muthukumaran Ganpathi Narayanan",
      "Neha Aggarwal",
      "Nipun Bhargava",
      "Partho Sarathi Mukherjee",
      "Pramod Kumar",
      "Rachna Bhargava",
      "Rachna Dogra",
      "Rajneesh Kumar Maurya",
      "Ramdas Atmaram Wani",
      "Richa Aggarwal",
      "Saloni Sharma",
      "Santosh Pant",
      "Shweta Rajput",
      "Sreeja Sreekanth",
      "Tulika Rawat",
      "Urvi Pritam",
      "Vimmi Sagar",
    ],
    faeCatA: [
      "Akta Chugh",
      "Alok Agrwal",
      "Disha Patel",
      "Mamta Pandey",
      "Manoj Pant",
      "Muthukumaran Ganpathi Narayanan",
      "Neha Aggarwal",
      "Nipun Bhargava",
      "Partho Sarathi Mukherjee",
      "Praveen Bhargava",
      "Rachna Bhargava",
      "Rachna Dogra",
      "Rahul Deshmukh",
      "Rajneesh Kumar Maurya",
      "Ramdas Atmaram Wani",
      "Saloni Sharma",
      "Santosh Pant",
      "Tulika Rawat",
    ],
    eac: [
      "Coal Mining",
      "Non-Coal Mining",
      "CRZ",
      "Hydro & River Valley",
      "Industry-1 (Mineral Based industries)",
      "Industry-2 (Petro-chemical & Distilleries)",
      "Industry-3 (Chemical Industries)",
      "Infrastructure-1",
      "Infrastructure-2",
      "Nuclear & Defence",
      "Thermal",
      "Violation Cases",
      "Andaman and Nicobar SEAC/SEIAA",
      "Andhra Pradesh SEAC/SEIAA",
      "Arunachal Pradesh SEAC/SEIAA",
      "Assam SEAC/SEIAA",
      "Bihar SEAC/SEIAA",
      "Chandigarh SEAC/SEIAA",
      "Chattisgarh SEAC/SEIAA",
      "Daman, Diu, Dadra and Nagar Haveli SEAC/SEIAA",
      "Delhi SEAC/SEIAA",
      "Goa SEAC/SEIAA",
      "Gujarat SEAC/SEIAA",
      "Haryana SEAC/SEIAA",
      "Himachal Pradesh SEAC/SEIAA",
      "Jammu & Kashmir SEAC/SEIAA",
      "Jharkhand SEAC/SEIAA",
      "Karnataka SEAC/SEIAA",
      "Kerala SEAC/SEIAA",
      "Ladakh SEAC/SEIAA",
      "Lakshadweep SEAC/SEIAA",
      "Madhya Pradesh SEAC/SEIAA",
      "Maharashtra SEAC/SEIAA",
      "Manipur SEAC/SEIAA",
      "Meghalaya SEAC/SEIAA",
      "Mizoram SEAC/SEIAA",
      "Nagaland SEAC/SEIAA",
      "Odisha SEAC/SEIAA",
      "Puducherry SEAC/SEIAA",
      "Punjab SEAC/SEIAA",
      "Rajasthan SEAC/SEIAA",
      "Sikkim SEAC/SEIAA",
      "Tamil Nadu SEAC/SEIAA",
      "Telangana SEAC/SEIAA",
      "Tripura SEAC/SEIAA",
      "Uttar Pradesh SEAC/SEIAA",
      "Uttarakhand SEAC/SEIAA",
      "West Bengal SEAC/SEIAA",
    ],
    eiaCoordinator: [
      "Alok Agrwal",
      "Anil Kumar",
      "Alok Agrwal",
      "Anil Kumar",
      "Deepika Arora",
      "Disha Patel",
      "Kantharaj Kempeena",
      "Muthukumaran Ganpathi Narayanan",
      "Neha Aggarwal",
      "Nipun Bhargava",
      "Partho Sarthi Mukherjee",
      "Praveen Bhargava",
      "Rachna Bhargava",
      "Rajneesh Kumar Maurya",
      "Ramdas Atmaram Wani",
      "Richa Aggarwal",
      "Saloni Sharma",
      "Santosh Pant",
      "Suresh Chandra Jain",
    ],
    country: [
      "Afghanistan",
      "Albania",
      "Algeria",
      "Andorra",
      "Angola",
      "Antigua and Barbuda",
      "Argentina",
      "Armenia",
      "Australia",
      "Austria",
      "Azerbaijan",
      "Bahamas",
      "Bahrain",
      "Bangladesh",
      "Barbados",
      "Belarus",
      "Belgium",
      "Belize",
      "Benin",
      "Bhutan",
      "Bolivia",
      "Bosnia and Herzegovina",
      "Botswana",
      "Brazil",
      "Brunei Darussalam",
      "Bulgaria",
      "Burkina Faso",
      "Burundi",
      "Cabo Verde",
      "Cambodia",
      "Cameroon",
      "Canada",
      "Central African Republic",
      "Chad",
      "Chile",
      "China",
      "Colombia",
      "Comoros",
      "Congo (Congo-Brazzaville)",
      "Costa Rica",
      "Croatia",
      "Cuba",
      "Cyprus",
      "Czechia (Czech Republic)",
      "Democratic Republic of the Congo",
      "Denmark",
      "Djibouti",
      "Dominica",
      "Dominican Republic",
      "Ecuador",
      "Egypt",
      "El Salvador",
      "Equatorial Guinea",
      "Eritrea",
      "Estonia",
      "Eswatini (fmr. 'Swaziland')",
      "Ethiopia",
      "Fiji",
      "Finland",
      "France",
      "Gabon",
      "Gambia",
      "Georgia",
      "Germany",
      "Ghana",
      "Greece",
      "Grenada",
      "Guatemala",
      "Guinea",
      "Guinea-Bissau",
      "Guyana",
      "Haiti",
      "Holy See",
      "Honduras",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Iraq",
      "Ireland",
      "Israel",
      "Italy",
      "Jamaica",
      "Japan",
      "Jordan",
      "Kazakhstan",
      "Kenya",
      "Kiribati",
      "Kuwait",
      "Kyrgyzstan",
      "Laos",
      "Latvia",
      "Lebanon",
      "Lesotho",
      "Liberia",
      "Libya",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Madagascar",
      "Malawi",
      "Malaysia",
      "Maldives",
      "Mali",
      "Malta",
      "Marshall Islands",
      "Mauritania",
      "Mauritius",
      "Mexico",
      "Micronesia",
      "Moldova",
      "Monaco",
      "Mongolia",
      "Montenegro",
      "Morocco",
      "Mozambique",
      "Myanmar (formerly Burma)",
      "Namibia",
      "Nauru",
      "Nepal",
      "Netherlands",
      "New Zealand",
      "Nicaragua",
      "Niger",
      "Nigeria",
      "North Korea",
      "North Macedonia (formerly Macedonia)",
      "Norway",
      "Oman",
      "Pakistan",
      "Palau",
      "Palestine State",
      "Panama",
      "Papua New Guinea",
      "Paraguay",
      "Peru",
      "Philippines",
      "Poland",
      "Portugal",
      "Qatar",
      "Romania",
      "Russia",
      "Rwanda",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Vincent and the Grenadines",
      "Samoa",
      "San Marino",
      "Sao Tome and Principe",
      "Saudi Arabia",
      "Senegal",
      "Serbia",
      "Seychelles",
      "Sierra Leone",
      "Singapore",
      "Slovakia",
      "Slovenia",
      "Solomon Islands",
      "Somalia",
      "South Africa",
      "South Korea",
      "South Sudan",
      "Spain",
      "Sri Lanka",
      "Sudan",
      "Suriname",
      "Sweden",
      "Switzerland",
      "Syria",
      "Tajikistan",
      "Tanzania",
      "Thailand",
      "Timor-Leste",
      "Togo",
      "Tonga",
      "Trinidad and Tobago",
      "Tunisia",
      "Turkey",
      "Turkmenistan",
      "Tuvalu",
      "Uganda",
      "Ukraine",
      "United Arab Emirates",
      "United Kingdom",
      "United States of America",
      "Uruguay",
      "Uzbekistan",
      "Vanuatu",
      "Venezuela",
      "Vietnam",
      "Yemen",
      "Zambia",
      "Zimbabwe",
    ],
    stateCode: [
      "AP",
      "AR",
      "AS",
      "BR",
      "CG",
      "GA",
      "GJ",
      "HR",
      "HP",
      "JH",
      "KA",
      "KL",
      "MP",
      "MH",
      "MN",
      "ML",
      "MZ",
      "NL",
      "OR",
      "PB",
      "RJ",
      "SK",
      "TN",
      "TG",
      "TR",
      "UP",
      "UT",
      "WB",
      "AN",
      "CH",
      "DN",
      "DD",
      "DL",
      "JK",
      "LA",
      "LD",
      "PY",
    ],
    pgCompany: ["PE", "PS", "PR", "PW"],
  };
  cache.put("dropdown_data_v1", JSON.stringify(data), 300); // cache 5 minutes
  return data;
}
/*
    --> Returns a JS object of arrays
    --> Uses CacheService so repeated form loads don’t hammer script execution
    --> We call this from the client side to populate selects (no duplication)
    --> Use "google.script.run" in a form page to populate dropdowns
*/
